spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/didacta
    username: didacta
    password: didacta
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/didacta
          jwk-set-uri: http://keycloak:8080/realms/didacta/protocol/openid-connect/certs
